server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot_activiti?useUnicode=true&characterEncoding=UTF-8&nullCatalogMeansCurrent=true&useOldAliasMetadataBehavior=true&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    #1.flase： 默认值。activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常
    #2.true： activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建
    #3.create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）
    #4.drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）
    database-schema-update: true
    #检测历史表是否存在 activiti7默认没有开启数据库历史记录 启动数据库历史记录
    db-history-used: true
    #记录历史等级 可配置的历史级别有none, activity, audit, full
    history-level: full
    #校验流程文件，默认校验resources下的processes文件夹里的流程文件
    check-process-definitions: false
    #流程定义文件存放目录
    process-definition-location-prefix: classpath:/processes/


# 日志相关配置
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info



  ## URL of the ActiveMQ broker. Auto-generated by default. For instance `tcp://localhost:61616`
  # failover:(tcp://localhost:61616,tcp://localhost:61617)
  # tcp://localhost:61616
jms:
  pub-sub-domain: true
activemq:
  broker-url: failover:tcp://127.0.0.1:61616
  in-memory: true
  pool:
    enabled: false
  packages:
    trust-all: true
  user: admin
  password: admin